/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Josechavez
 */
public class Ventana_Administrador extends javax.swing.JFrame {
 Controlador c = new Controlador();
    /**
     * Creates new form Ventana_Administrador
     */
    public Ventana_Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InicioAdm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        SdIniciAdm = new javax.swing.JPanel();
        AlquilerAdm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblAlquilerAdm = new javax.swing.JLabel();
        SdAlquilerAdm = new javax.swing.JPanel();
        MovimientoAdm = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblMovimientoAdm = new javax.swing.JLabel();
        SdMovimientoAdm = new javax.swing.JPanel();
        ConsultaAdm = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lvlConsultaADm = new javax.swing.JLabel();
        SdConsultaAdm = new javax.swing.JPanel();
        ReportAdm = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblReporteAdm = new javax.swing.JLabel();
        SdReporteAdm = new javax.swing.JPanel();
        CrearAdm = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblCrearAdm = new javax.swing.JLabel();
        SdCrearAdm = new javax.swing.JPanel();
        SalirAdm = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(207, 216, 220));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InicioAdm.setBackground(new java.awt.Color(69, 90, 100));
        InicioAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Home_32px.png"))); // NOI18N
        InicioAdm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblInicio.setBackground(new java.awt.Color(255, 255, 255));
        lblInicio.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInicioMousePressed(evt);
            }
        });
        InicioAdm.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2, 170, 50));

        SdIniciAdm.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout SdIniciAdmLayout = new javax.swing.GroupLayout(SdIniciAdm);
        SdIniciAdm.setLayout(SdIniciAdmLayout);
        SdIniciAdmLayout.setHorizontalGroup(
            SdIniciAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SdIniciAdmLayout.setVerticalGroup(
            SdIniciAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        InicioAdm.add(SdIniciAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jPanel1.add(InicioAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, 50));

        AlquilerAdm.setBackground(new java.awt.Color(69, 90, 100));
        AlquilerAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Wi-Fi_32px.png"))); // NOI18N
        AlquilerAdm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        lblAlquilerAdm.setBackground(new java.awt.Color(204, 204, 204));
        lblAlquilerAdm.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblAlquilerAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblAlquilerAdm.setText("Alquilar habitacion");
        lblAlquilerAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAlquilerAdmMousePressed(evt);
            }
        });
        AlquilerAdm.add(lblAlquilerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 54));

        SdAlquilerAdm.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout SdAlquilerAdmLayout = new javax.swing.GroupLayout(SdAlquilerAdm);
        SdAlquilerAdm.setLayout(SdAlquilerAdmLayout);
        SdAlquilerAdmLayout.setHorizontalGroup(
            SdAlquilerAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SdAlquilerAdmLayout.setVerticalGroup(
            SdAlquilerAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        AlquilerAdm.add(SdAlquilerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(AlquilerAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 50));

        MovimientoAdm.setBackground(new java.awt.Color(69, 90, 100));
        MovimientoAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Money_32px.png"))); // NOI18N
        MovimientoAdm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblMovimientoAdm.setBackground(new java.awt.Color(204, 204, 204));
        lblMovimientoAdm.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblMovimientoAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblMovimientoAdm.setText("Movimiento de caja");
        lblMovimientoAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMovimientoAdmMousePressed(evt);
            }
        });
        MovimientoAdm.add(lblMovimientoAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 54));

        SdMovimientoAdm.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout SdMovimientoAdmLayout = new javax.swing.GroupLayout(SdMovimientoAdm);
        SdMovimientoAdm.setLayout(SdMovimientoAdmLayout);
        SdMovimientoAdmLayout.setHorizontalGroup(
            SdMovimientoAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SdMovimientoAdmLayout.setVerticalGroup(
            SdMovimientoAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        MovimientoAdm.add(SdMovimientoAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(MovimientoAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 50));

        ConsultaAdm.setBackground(new java.awt.Color(69, 90, 100));
        ConsultaAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Document_32px.png"))); // NOI18N
        ConsultaAdm.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        lvlConsultaADm.setBackground(new java.awt.Color(204, 204, 204));
        lvlConsultaADm.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lvlConsultaADm.setForeground(new java.awt.Color(255, 255, 255));
        lvlConsultaADm.setText("Consultas");
        lvlConsultaADm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lvlConsultaADmMousePressed(evt);
            }
        });
        ConsultaAdm.add(lvlConsultaADm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 56));

        SdConsultaAdm.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout SdConsultaAdmLayout = new javax.swing.GroupLayout(SdConsultaAdm);
        SdConsultaAdm.setLayout(SdConsultaAdmLayout);
        SdConsultaAdmLayout.setHorizontalGroup(
            SdConsultaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SdConsultaAdmLayout.setVerticalGroup(
            SdConsultaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ConsultaAdm.add(SdConsultaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(ConsultaAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 50));

        ReportAdm.setBackground(new java.awt.Color(69, 90, 100));
        ReportAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Print_32px.png"))); // NOI18N
        ReportAdm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 12, -1, -1));

        lblReporteAdm.setBackground(new java.awt.Color(204, 204, 204));
        lblReporteAdm.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblReporteAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteAdm.setText("Reportes");
        lblReporteAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblReporteAdmMousePressed(evt);
            }
        });
        ReportAdm.add(lblReporteAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 162, 56));

        SdReporteAdm.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout SdReporteAdmLayout = new javax.swing.GroupLayout(SdReporteAdm);
        SdReporteAdm.setLayout(SdReporteAdmLayout);
        SdReporteAdmLayout.setHorizontalGroup(
            SdReporteAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SdReporteAdmLayout.setVerticalGroup(
            SdReporteAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        ReportAdm.add(SdReporteAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(ReportAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        CrearAdm.setBackground(new java.awt.Color(69, 90, 100));
        CrearAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Male User_32px.png"))); // NOI18N
        CrearAdm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        lblCrearAdm.setBackground(new java.awt.Color(204, 204, 204));
        lblCrearAdm.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblCrearAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblCrearAdm.setText("Crear empleado");
        lblCrearAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCrearAdmMousePressed(evt);
            }
        });
        CrearAdm.add(lblCrearAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 53));

        SdCrearAdm.setBackground(new java.awt.Color(69, 90, 100));

        javax.swing.GroupLayout SdCrearAdmLayout = new javax.swing.GroupLayout(SdCrearAdm);
        SdCrearAdm.setLayout(SdCrearAdmLayout);
        SdCrearAdmLayout.setHorizontalGroup(
            SdCrearAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SdCrearAdmLayout.setVerticalGroup(
            SdCrearAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        CrearAdm.add(SdCrearAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(CrearAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 50));

        SalirAdm.setBackground(new java.awt.Color(255, 82, 82));
        SalirAdm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Multiply_32px.png"))); // NOI18N
        SalirAdm.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 42));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Salir");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        SalirAdm.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 168, 42));

        jPanel1.add(SalirAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 220, 50));

        jPanel2.setBackground(new java.awt.Color(69, 90, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Minimize Window_32px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1296, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 50));

        jDesktopPane2.setBackground(new java.awt.Color(207, 216, 220));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 1120, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMousePressed
        c.setColor(InicioAdm,SdIniciAdm,lblInicio);
        c.resetColorJPanel(new JPanel[]{AlquilerAdm,SdAlquilerAdm,MovimientoAdm,SdMovimientoAdm,ConsultaAdm,SdConsultaAdm,ReportAdm,SdReporteAdm,CrearAdm,SdCrearAdm});
        c.resetColorLabel(new JLabel[]{lblAlquilerAdm,lblMovimientoAdm,lvlConsultaADm,lblReporteAdm,lblCrearAdm});
    }//GEN-LAST:event_lblInicioMousePressed

    private void lblAlquilerAdmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlquilerAdmMousePressed
        c.setColor(AlquilerAdm,SdAlquilerAdm,lblAlquilerAdm);
        c.resetColorJPanel(new JPanel[]{InicioAdm,SdIniciAdm,MovimientoAdm,SdMovimientoAdm,ConsultaAdm,SdConsultaAdm,ReportAdm,SdReporteAdm,CrearAdm,SdCrearAdm});
        c.resetColorLabel(new JLabel[]{lblInicio,lblMovimientoAdm,lvlConsultaADm,lblReporteAdm,lblCrearAdm});
    }//GEN-LAST:event_lblAlquilerAdmMousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        c.salir();
    }//GEN-LAST:event_jLabel14MousePressed

    private void lblMovimientoAdmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovimientoAdmMousePressed
        c.setColor(MovimientoAdm,SdMovimientoAdm,lblMovimientoAdm);
        c.resetColorJPanel(new JPanel[]{InicioAdm,SdIniciAdm,AlquilerAdm,SdAlquilerAdm,ConsultaAdm,SdConsultaAdm,ReportAdm,SdReporteAdm,CrearAdm,SdCrearAdm});
        c.resetColorLabel(new JLabel[]{lblInicio,lblAlquilerAdm,lvlConsultaADm,lblReporteAdm,lblCrearAdm});
    }//GEN-LAST:event_lblMovimientoAdmMousePressed

    private void lvlConsultaADmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvlConsultaADmMousePressed
        c.setColor(ConsultaAdm,SdConsultaAdm,lvlConsultaADm);
        c.resetColorJPanel(new JPanel[]{InicioAdm,SdIniciAdm,AlquilerAdm,SdAlquilerAdm,MovimientoAdm,SdMovimientoAdm,ReportAdm,SdReporteAdm,CrearAdm,SdCrearAdm});
        c.resetColorLabel(new JLabel[]{lblInicio,lblAlquilerAdm,lblMovimientoAdm,lblReporteAdm,lblCrearAdm});
   
    }//GEN-LAST:event_lvlConsultaADmMousePressed

    private void lblReporteAdmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteAdmMousePressed
        c.setColor(ReportAdm,SdReporteAdm,lblReporteAdm);
        c.resetColorJPanel(new JPanel[]{InicioAdm,SdIniciAdm,AlquilerAdm,SdAlquilerAdm,MovimientoAdm,SdMovimientoAdm,ConsultaAdm,SdConsultaAdm,CrearAdm,SdCrearAdm});
        c.resetColorLabel(new JLabel[]{lblInicio,lblAlquilerAdm,lblMovimientoAdm,lvlConsultaADm,lblCrearAdm});
     
    }//GEN-LAST:event_lblReporteAdmMousePressed

    private void lblCrearAdmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearAdmMousePressed
       c.setColor(CrearAdm,SdCrearAdm,lblCrearAdm);
        c.resetColorJPanel(new JPanel[]{InicioAdm,SdIniciAdm,AlquilerAdm,SdAlquilerAdm,MovimientoAdm,SdMovimientoAdm,ConsultaAdm,SdConsultaAdm,ReportAdm,SdReporteAdm});
        c.resetColorLabel(new JLabel[]{lblInicio,lblAlquilerAdm,lblMovimientoAdm,lvlConsultaADm,lblReporteAdm});
    }//GEN-LAST:event_lblCrearAdmMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windos".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlquilerAdm;
    private javax.swing.JPanel ConsultaAdm;
    private javax.swing.JPanel CrearAdm;
    private javax.swing.JPanel InicioAdm;
    private javax.swing.JPanel MovimientoAdm;
    private javax.swing.JPanel ReportAdm;
    private javax.swing.JPanel SalirAdm;
    private javax.swing.JPanel SdAlquilerAdm;
    private javax.swing.JPanel SdConsultaAdm;
    private javax.swing.JPanel SdCrearAdm;
    private javax.swing.JPanel SdIniciAdm;
    private javax.swing.JPanel SdMovimientoAdm;
    private javax.swing.JPanel SdReporteAdm;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAlquilerAdm;
    private javax.swing.JLabel lblCrearAdm;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblMovimientoAdm;
    private javax.swing.JLabel lblReporteAdm;
    private javax.swing.JLabel lvlConsultaADm;
    // End of variables declaration//GEN-END:variables
}
